name: Build and Push API
on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - '.github/workflows/build-and-push-api.yml'
      - 'DockerfileRocket'
      - '.scarb-version'
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  DOCKER_REGISTRY: nethermind.jfrog.io
  REPO_DEV: nubia-oci-local-dev
  REPO_STAGING: nubia-oci-local-staging
  REPO_PROD: nubia-oci-local-prod
  NODE_VERSION: '20.x'
  PROD_BUCKET_NAME: 'starknet-remix-plugin-prod'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up ORAS
        uses: oras-project/setup-oras@v1

      - name: Verify ORAS version
        run: oras version

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.ARTIFACTORY_NUBIA_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_NUBIA_TOKEN_DEVELOPER }}

      - name: Login to registry with ORAS
        run: |
          oras login ${{ env.DOCKER_REGISTRY }} \
            -u ${{ secrets.ARTIFACTORY_NUBIA_USERNAME }} \
            -p ${{ secrets.ARTIFACTORY_NUBIA_TOKEN_DEVELOPER }}

      - name: Get Scarb version
        id: get_scarb_version
        run: |
          SCARB_VERSION=$(cat .scarb-version | sed 's/v//') 
          echo "scarb_version=${SCARB_VERSION}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: "linux/amd64"
          push: true
          file: ./DockerfileRocket
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.REPO_DEV }}/starknet-remix-apiserver:${{ github.sha }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.REPO_DEV }}/starknet-remix-apiserver:latest
          build-args: |
            SCARB_VERSION=${{ env.scarb_version }}