name: Build and Push API
on:
  push:
    branches:
      - feature/update_deployment_pipelines
    paths:
      - 'api/**'
      - '.github/workflows/build-and-push-api.yml'
      - 'DockerfileRocket'
      - '.scarb-version'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  DOCKER_REGISTRY: nethermind.jfrog.io
  IMAGE_NAME: starknet-remix-apiserver
  REPO: nubia-oci-local-dev

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Define image tag
        run: |
          TAG=$(git describe --tags --always)
          echo "DOCKER_IMAGE_TAG=$TAG" >> $GITHUB_ENV
          echo "TAG: $TAG"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.ARTIFACTORY_NUBIA_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_NUBIA_TOKEN_DEVELOPER }}

      - name: Get Scarb version
        id: get_scarb_version
        run: |
          SCARB_VERSION=$(cat .scarb-version | sed 's/v//') 
          echo "scarb_version=${SCARB_VERSION}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: "linux/amd64"
          push: true
          file: ./DockerfileRocket
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.REPO }}/starknet-remix-apiserver:${{ github.sha }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            SCARB_VERSION=${{ env.scarb_version }}